[package]
name = "kokonaisuus"
version = "0.1.0"
authors = ["Ilari Tommiska <ilari97@hotmail.com>"]
edition = "2018"

[features]
default = []
examples = []
step_0 = []
step_1 = []
step_2 = []
step_3 = []
step_4 = []
step_5 = []
step_6 = []

[dependencies]
